# Elasticsearch
# PostgreSQL 9.1 and 9.2
#
# VERSION               0.0.1

FROM fgrehm/ventriloquist-base
MAINTAINER Fabio Rehm "fgrehm@gmail.com"

RUN apt-get install -y openjdk-7-jre-headless && apt-get clean
